name: Auto Release

on:
  push:
    tags:
      - 'v*'  # 以 v 开头的 tag，比如 v1.0.0，v2.3.4 等

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip the release directory
        run: |
          cd custom_components/mcp_bridge
          zip -r ../../mcp_bridge.zip ./*

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: mcp_bridge.zip
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}